embed_assets: off
gzip_assets: off

# libsass does this for us
compress_assets: off

# if you want use IE in dev mode and want to get around the max of 30 stylesheets
# problem, uncomment the following lines and make sure you
# rm -rf public/assets after you make any changes to css
# package_assets: always
# compress_assets: off

<% require File.expand_path(Jammit::ASSET_ROOT + '/lib/canvas/plugins/plugin_assets') %>
<% plugin_assets = PluginAssets.new %>
<%= plugin_assets.bundle_yml %>


stylesheets:
  saml_fields:
    - public/stylesheets/compiled/bundles/saml_fields.css
  course_wizard:
    - public/stylesheets/compiled/bundles/course_wizard.css
  react_files:
    - public/stylesheets/compiled/bundles/react_files.css
  instructure_eportfolio:
    - public/stylesheets/compiled/bundles/instructure_eportfolio.css
  course_show:
    - public/stylesheets/compiled/bundles/course_show.css
  course_list:
    - public/stylesheets/compiled/bundles/course_list.css
  content_migrations:
    - public/stylesheets/compiled/bundles/content_migrations.css
  vendor:
    - public/stylesheets/compiled/bundles/vendor.css
  common:
    - public/stylesheets/compiled/bundles/common.css
  context_modules:
    - public/stylesheets/compiled/bundles/context_modules.css
  context_modules2:
    - public/stylesheets/compiled/bundles/context_modules2.css
  modules_next:
    - public/stylesheets/compiled/bundles/modules_next.css
  context_module_progressions:
    - public/stylesheets/compiled/bundles/context_module_progressions.css
  dashboard:
    - public/stylesheets/compiled/bundles/dashboard.css
  registration:
    - public/stylesheets/compiled/bundles/registration.css
  profile_show:
    - public/stylesheets/compiled/bundles/profile_show.css
  profile_edit:
    - public/stylesheets/compiled/bundles/profile_edit.css
  facebook:
    - public/stylesheets/compiled/bundles/facebook.css
  speed_grader:
    - public/stylesheets/compiled/bundles/speed_grader.css
  conferences:
    - public/stylesheets/compiled/bundles/conferences.css
  gradebook_uploads:
    - public/stylesheets/compiled/bundles/gradebook_uploads.css
  calendar2:
    - public/stylesheets/compiled/bundles/calendar2.css
  agenda_view:
    - public/stylesheets/compiled/bundles/agenda_view.css
  course_settings:
    - public/stylesheets/compiled/bundles/course_settings.css
  discussions:
    - public/stylesheets/compiled/bundles/discussions.css
  discussions_list:
    - public/stylesheets/compiled/bundles/discussions_list.css
  full_files:
    - public/stylesheets/compiled/bundles/full_files.css
  datagrid:
    - public/stylesheets/compiled/bundles/datagrid.css
  gradebook_history:
    - public/stylesheets/compiled/bundles/gradebook_history.css
  gradebook2:
    - public/stylesheets/compiled/bundles/gradebook2.css
  screenreader_gradebook:
    - public/stylesheets/compiled/bundles/screenreader_gradebook.css
  attendance:
    - public/stylesheets/compiled/bundles/attendance.css
  quizzes:
    - public/stylesheets/compiled/bundles/quizzes.css
  quizzes_ember:
    - public/stylesheets/compiled/bundles/quizzes_ember.css
  moderate_quiz:
    - public/stylesheets/compiled/bundles/moderate_quiz.css
  assignments:
    - public/stylesheets/compiled/bundles/assignments.css
  assignments_edit:
    - public/stylesheets/compiled/bundles/assignments_edit.css
  new_assignments:
    - public/stylesheets/compiled/bundles/new_assignments.css
  grading_standards:
    - public/stylesheets/compiled/bundles/grading_standards.css
  grading_periods:
    - public/stylesheets/compiled/bundles/grading_periods.css
  login:
    - public/stylesheets/compiled/bundles/login.css
  otp_login:
    - public/stylesheets/compiled/bundles/otp_login.css
  roster:
    - public/stylesheets/compiled/bundles/roster.css
  roster_user:
    - public/stylesheets/compiled/bundles/roster_user.css
  learning_outcomes:
    - public/stylesheets/compiled/bundles/learning_outcomes.css
  grade_summary:
    - public/stylesheets/compiled/bundles/grade_summary.css
  context_list:
    - public/stylesheets/compiled/bundles/context_list.css
  page_views:
    - public/stylesheets/compiled/bundles/page_views.css
  prior_users:
    - public/stylesheets/compiled/bundles/prior_users.css
  reports:
    - public/stylesheets/compiled/bundles/reports.css
  statistics:
    - public/stylesheets/compiled/bundles/statistics.css
  slickgrid:
    - public/stylesheets/compiled/bundles/slickgrid.css
  sub_accounts:
    - public/stylesheets/compiled/bundles/sub_accounts.css
  user_grades:
    - public/stylesheets/compiled/bundles/user_grades.css
  user_logins:
    - public/stylesheets/compiled/bundles/user_logins.css
  account_settings:
    - public/stylesheets/compiled/bundles/account_settings.css
  account_admin_tools:
    - public/stylesheets/compiled/bundles/account_admin_tools.css
  select_content_dialog:
    - public/stylesheets/compiled/bundles/select_content_dialog.css
  conversations_new:
    - public/stylesheets/compiled/bundles/conversations_new.css
  alerts:
    - public/stylesheets/compiled/bundles/alerts.css
  developer_keys:
    - public/stylesheets/compiled/bundles/developer_keys.css
  edit_calendar_event_full:
    - public/stylesheets/compiled/bundles/edit_calendar_event_full.css
  notification_preferences:
    - public/stylesheets/compiled/bundles/notification_preferences.css
  tinymce:
    - public/stylesheets/compiled/bundles/tinymce.css
  messages:
    - public/stylesheets/compiled/bundles/messages.css
  user_notes:
    - public/stylesheets/compiled/bundles/user_notes.css
  imports:
    - public/stylesheets/compiled/bundles/imports.css
  styleguide:
    - public/stylesheets/compiled/bundles/styleguide.css
  locale:
    - public/stylesheets/compiled/bundles/locale.css
  mobile_auth:
    - public/stylesheets/compiled/bundles/mobile_auth.css
  all_courses:
    - public/stylesheets/compiled/bundles/all_courses.css
  external_tool_full_width:
    - public/stylesheets/compiled/bundles/external_tool_full_width.css
  dashboard_card:
    - public/stylesheets/compiled/bundles/dashboard_card.css
  terms:
    - public/stylesheets/compiled/bundles/terms.css
  wiki_page:
    - public/stylesheets/compiled/bundles/wiki_page.css
  # Client Apps:
  canvas_quizzes:
    - public/stylesheets/compiled/bundles/canvas_quizzes.css

  <%= plugin_assets.anchors_yml %>
